apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silverbullet.fullname" . }}
  labels:
    {{- include "silverbullet.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.admin.username }}
  {{- $sbUser := print .Values.admin.username ":" .Values.admin.password }}
  SB_USER: {{ $sbUser | b64enc }}
{{- end -}}
{{- if .Values.runMode.syncOnly }}
  SB_READ_ONLY: {{ ternary "true" "false" .Values.runMode.syncOnly | b64enc }}
{{- end -}}
{{- if .Values.runMode.readOnly }}
  SB_READ_ONLY: {{ ternary "true" "false" .Values.runMode.readOnly | b64enc }}
{{- end -}}
{{- if .Values.git.name }}
  GIT_NAME: {{ .Values.git.name | b64enc }}
{{- end -}}
{{- if .Values.git.email }}
  GIT_EMAIL: {{ .Values.git.email | b64enc }}
{{- end -}}
{{- if .Values.git.repository }}
  GIT_REPOSITORY: {{ .Values.git.repository | b64enc }}
{{- end -}}
{{- if .Values.init.repository }}
  INIT_REPOSITORY: {{ .Values.init.repository | b64enc }}
{{ end -}}
{{- if .Values.ssh }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silverbullet.fullname" . }}-ssh
  labels:
    {{- include "silverbullet.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.ssh }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
